TelefonAksesuar/Models/Urunler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonAksesuar.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int UrunID { get; set; }
        public string Kategori { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Fiyat { get; set; }
        public string Stok { get; set; }
        public string Resim { get; set; }

        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}

TelefonAksesuar/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using TelefonAksesuar.Models;

namespace TelefonAksesuar.Controllers
{


    public class UrunlerController : Controller
    {
        private TelefonAksesuarEntities db = new TelefonAksesuarEntities();

        public ActionResult Index(string arama)
        {
            //arama

            var urunler = from s in db.Urunler select s;
            if(!String.IsNullOrEmpty(arama))
            {
                urunler = urunler.Where(s => s.Marka.ToUpper().Contains(arama.ToUpper()) || s.Kategori.ToUpper().Contains(arama.ToUpper())
                                            || s.Model.ToUpper().Contains(arama.ToUpper()) || (s.Marka+" "+s.Model).ToUpper().Contains(arama.ToUpper()) );
            }
            //          

            ViewData["arananKelime"] = arama;
            return View(urunler.ToList());
        }

        public ActionResult SarjCihazlari()
        {
            var SarjCihazlari = db.Urunler.ToList();
            return View(SarjCihazlari);
        }

        public ActionResult Kulakliklar()
        {

            var Kulakliklar = db.Urunler.ToList();
            return View(Kulakliklar);
        }

        public ActionResult Kiliflar()
        {
            var Kiliflar = db.Urunler.ToList();
            return View(Kiliflar);
        }

        public ActionResult UrunDetay(int id)
        {
            ViewBag.urunID = id;
            ViewBag.Urunler = db.Urunler.ToList();

            ViewBag.Yorumlar = db.Yorumlar.ToList();

           
            return View();
        }
        public ActionResult YorumEkle(int urunID,string kadi,string tarih,Yorumlar model)
        {
            if (ModelState.IsValid) // formdaki kontroller istenilen şekildeyse ( Required vs gibi)
            {
                TelefonAksesuar.Models.TelefonAksesuarEntities db = new Models.TelefonAksesuarEntities();
                Yorumlar yorumModel = new Yorumlar();                      //KAYIT İŞLEMİ      Postla alınanlar ekleniyor
                yorumModel.UrunID = urunID;
                yorumModel.KullaniciAdi = kadi;
                yorumModel.YorumTarih = tarih;
                yorumModel.Yorum = model.Yorum;

                db.Yorumlar.Add(yorumModel);

                db.SaveChanges();
            }

                return RedirectToAction("UrunDetay",new { id = urunID });
        }
        public ActionResult SepeteEkle(int Uyeid, string urunAd, int fiyat)
        {
            TelefonAksesuar.Models.TelefonAksesuarEntities db = new Models.TelefonAksesuarEntities();
            if (Session["yetki"] == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            else if (Session["yetki"].ToString() == "admin")
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            else
            {
                Sepetim sepet = new Sepetim();
                sepet.UyeID = Uyeid;
                sepet.UrunAd = urunAd;
                sepet.Adet = 1;
                sepet.Fiyat = fiyat;
                sepet.ToplamFiyat = sepet.Adet * fiyat;


                db.Sepetim.Add(sepet);
                db.SaveChanges();

                return RedirectToAction("Index", "Sepet");
            }
                   
        }
       
    }
}

TelefonAksesuar/Views/Urunler/Index.cshtml
@model IEnumerable<TelefonAksesuar.Models.Urunler>

@{
    ViewBag.Title = "Arama Sonucu";
}

<h2></h2>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
               " @ViewData["arananKelime"] " - Arama Sonuçları
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Anasayfa", "Index", "Home")
                </li>
                <li class="active">Arama</li>
            </ol>
        </div>
    </div>

    <div class="row">

        @{  string aranan;
            if (@ViewData["arananKelime"] == null) { aranan = null; }
            else { aranan = @ViewData["arananKelime"].ToString(); }
        }
            @foreach (var urun in Model)
            {

                <div class="col-md-3 portfolio-item">
                    <a href="@Url.Action("UrunDetay","Urunler", new { id = urun.UrunID })">
                        <img src="~/Images/Urunler/@urun.Resim" class="img-responsive" style="height:150px">
                    </a>
                    <h3>
                        
                            @if (@urun.Marka.ToUpper() == @aranan.ToUpper())
                            {  <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })" style="background-color:lightgray"> @urun.Marka</a>  }
                            else
                            {
                                <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })">@urun.Marka</a>
                            }
                            @if (urun.Model.ToUpper() == aranan.ToUpper())
                            { <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })" style="background-color:lightgray"> @urun.Model</a>  }
                            else
                            {
                                <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })">@urun.Model</a>
                            }
                                                   
                    </h3>
                    <p>Fiyat:@urun.Fiyat TL</p>
                    <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })" class="btn btn-primary">Ürün Detayı <i class="fa fa-angle-right"></i></a>
                </div>
         
          }
      


    </div>

</div>
   

TelefonAksesuar/Views/Urunler/Kiliflar.cshtml
@model IEnumerable<TelefonAksesuar.Models.Urunler>
@{
    ViewBag.Title = @TelefonAksesuar.Resources.lang.Kılıflar;
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
               @TelefonAksesuar.Resources.lang.Kılıflar
                <small>@TelefonAksesuar.Resources.lang.KaliteliVeŞık</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink(TelefonAksesuar.Resources.lang.Anasayfa, "Index", "Home")
                </li>
                <li class="active">@TelefonAksesuar.Resources.lang.Kılıflar</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">

        
        @foreach (var urun in Model)
        {
            if (urun.Kategori == "Kılıf")
            {
                <div class="col-md-4 portfolio-item">
                    <a href="@Url.Action("UrunDetay","Urunler", new { id = urun.UrunID })">
                      <img src="~/Images/Urunler/@urun.Resim" class="img-responsive" style="height:250px">
                    </a>
                    <h3>
                        <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })">@urun.Marka  @urun.Model</a>
                    </h3>
                    <p>@TelefonAksesuar.Resources.lang.Fiyat :@urun.Fiyat @TelefonAksesuar.Resources.lang.ParaBirimi</p>
                    <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })" class="btn btn-primary">@TelefonAksesuar.Resources.lang.UrunDetayı <i class="fa fa-angle-right"></i></a>
                </div>
               
            }
        }
       

        
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

TelefonAksesuar/Views/Urunler/Kulakliklar.cshtml
@model IEnumerable<TelefonAksesuar.Models.Urunler>
@{
    ViewBag.Title = TelefonAksesuar.Resources.lang.Kulaklıklar;
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @TelefonAksesuar.Resources.lang.Kulaklıklar
                <small>@TelefonAksesuar.Resources.lang.KaliteliVeŞık</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink(TelefonAksesuar.Resources.lang.Anasayfa, "Index", "Home")
                </li>
                <li class="active">@TelefonAksesuar.Resources.lang.Kulaklıklar</li>
            </ol>
        </div>
    </div>
    <div class="row">

        @foreach (var urun in Model)
        {
            if (urun.Kategori == "Kulaklık")
            {
                <div class="col-md-6 portfolio-item">
                    <a href="@Url.Action("UrunDetay","Urunler", new { id = urun.UrunID })">
                        <img src="~/Images/Urunler/@urun.Resim" class="img-responsive" style="height:250px">
                    </a>
                    <h3>
                        <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })">@urun.Marka  @urun.Model</a>
                    </h3>
                    <p>@TelefonAksesuar.Resources.lang.Fiyat : @urun.Fiyat @TelefonAksesuar.Resources.lang.ParaBirimi</p>
                    <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })" class="btn btn-primary">@TelefonAksesuar.Resources.lang.UrunDetayı <i class="fa fa-angle-right"></i></a>
                </div>
            }
        }
        
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

TelefonAksesuar/Views/Urunler/SarjCihazlari.cshtml
@{
    ViewBag.Title = @TelefonAksesuar.Resources.lang.ŞarjCihazları;
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @TelefonAksesuar.Resources.lang.ŞarjCihazları
                <small>@TelefonAksesuar.Resources.lang.KaliteliVeŞık</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                  @Html.ActionLink(TelefonAksesuar.Resources.lang.Anasayfa, "Index", "Home")
                </li>
                <li class="active">@TelefonAksesuar.Resources.lang.ŞarjCihazları</li>
            </ol>
        </div>
    </div>

        @foreach (var urun in Model)
        {
            if (urun.Kategori == "Sarj Cihazı")
            {
                <div class="row">
                    <div class="col-md-7">
                        <a href="@Url.Action("UrunDetay","Urunler", new { id = urun.UrunID })">
                            <img src="~/Images/Urunler/@urun.Resim" class="img-responsive" style="height:350px">
                        </a>
                    </div>
                    <div class="col-md-5">
                        <h3>@urun.Marka </h3>
                        <h4>@urun.Model</h4>
                        <p>@TelefonAksesuar.Resources.lang.Fiyat : @urun.Fiyat @TelefonAksesuar.Resources.lang.ParaBirimi</p>
                        <a href="@Url.Action("UrunDetay", "Urunler", new { id = urun.UrunID })" class="btn btn-primary">@TelefonAksesuar.Resources.lang.UrunDetayı <i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
                <hr>

            }
        }

    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

TelefonAksesuar/Views/Urunler/UrunDetay.cshtml
@model TelefonAksesuar.Models.Yorumlar


@foreach (var urun in ViewBag.Urunler)
{
    if (urun.UrunID == ViewBag.urunID)
    {
        @urun.UrunID;

        ViewBag.Title = @urun.Marka + " " + @urun.Model + " " + @urun.Kategori;

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @urun.Marka @urun.Model
               
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Anasayfa", "Index", "Home")
                </li>
                
                <li class="active">@urun.Kategori</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <img src="~/Images/Urunler/@urun.Resim" class="img-responsive">
        </div>
        
        <div class="col-md-4">
            <h3>@urun.Marka @urun.Model @urun.Kategori</h3>

            <ul>
                <li>Fiyat : @urun.Fiyat  TL     </li>
            </ul>
            

            @if (Session["id"] != null)
            {
                <a href="@Url.Action("SepeteEkle", "Urunler", new { Uyeid = Session["id"], urunAd = urun.Marka + " " + urun.Model + " " + urun.Kategori, fiyat = urun.Fiyat })" class="btn btn-primary">Sepete Ekle </a>
            }
            else
            {
                <br /><br /><h4><font style="color:red">**Ürünü sepetinize ekleyebilmek için sisteme  @Html.ActionLink("Giriş", "Index", "Giris")  yapmalısınız</font></h4>
            }
        </div>
    </div>
    <div class="row">
       
        <hr>
        <!-- yorumlar -->
        @{
            int yorumSayisi = 0;
        }

        @foreach (var yorum in ViewBag.Yorumlar)
        {
            if (yorum.UrunID == ViewBag.urunID)
            {
                <blockquote>
                    <p>@yorum.Yorum</p>
                    <small>@yorum.KullaniciAdi tarafından @yorum.YorumTarih </small>
                </blockquote>

                yorumSayisi++;
            }
        }
        @if (yorumSayisi == 0)
        {
            <label> Bu ürün hakkında yorum yapılmamış.</label>
        }

        <hr>
        <!-- yorum yazma kutusu-->
        @if (Session["kadi"] != null)
        {
            <div class="well">
                <h4>Yorumunuz:</h4>

                @using (Html.BeginForm("YorumEkle", "Urunler", new { urunID = urun.UrunID, kadi = Session["kadi"].ToString(), tarih = DateTime.Now.ToString() }))
                {
                    <div class="form-group">
                        @Html.TextAreaFor(m => m.Yorum, new { @class = "form-control", cols = 30, rows = 3, style = "resize:none" })@Html.ValidationMessageFor(m => m.Yorum)
                    </div>
                    <button class="btn btn-primary" type="submit">Yaz</button>
                }

            </div>
        }

    </div>
</div>

        }
    }