TelefonAksesuar/Controllers/ProfilController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TelefonAksesuar.Models;

namespace TelefonAksesuar.Controllers
{
    public class ProfilController : Controller
    {
        private TelefonAksesuarEntities db = new TelefonAksesuarEntities();

        // GET: Profil
        public ActionResult Index()
        {
            if (Session["yetki"] == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }        
            else
            {
                return View(db.Uyeler.ToList());
            }
           
        }


        // GET: Profil/Edit/5
        public ActionResult Duzenle(int? id)
        {
            if (Session["yetki"] == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }          
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Uyeler uyeler = db.Uyeler.Find(id);
                if (uyeler == null)
                {
                    return HttpNotFound();
                }
                return View(uyeler);
            }
        }

        // POST: Profil/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Duzenle([Bind(Include = "UyeID,Ad,Soyad,EMail,KullaniciAdi,Sifre,Yas,Sehir,Adres,Yetki")] Uyeler uyeler)
        {
            if (Session["yetki"] == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }      
            else
            {
                if (ModelState.IsValid)
                {
                    db.Entry(uyeler).State = EntityState.Modified;
                    db.SaveChanges();
                    Session["adres"] = uyeler.Adres;
                    Session["ad"] = uyeler.Ad;
                    Session["kadi"] = uyeler.KullaniciAdi;
                    return RedirectToAction("Index");
                }
                return View(uyeler);
            }
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TelefonAksesuar/Controllers/SiparisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TelefonAksesuar.Models;

namespace TelefonAksesuar.Controllers
{
    public class SiparisController : Controller
    {
        private TelefonAksesuarEntities db = new TelefonAksesuarEntities();
       
        public ActionResult Index()
        {
            
            if (Session["yetki"] == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            else if (Session["yetki"].ToString() == "admin")
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            else
            {
                var siparisler = db.Siparisler.ToList();
                return View(siparisler);
            }
        }
        public ActionResult Ekle(int Uyeid,string Ozet,string Adres,int Fiyat)
        {
            TelefonAksesuar.Models.TelefonAksesuarEntities db = new Models.TelefonAksesuarEntities();
            if (Session["yetki"] == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            else if (Session["yetki"].ToString() == "admin")
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            else
            {
                Siparisler siparis = new Siparisler();      //Sİpariş tablosuna veriler eklenir

                siparis.SiparisOzet = Ozet;
                siparis.UyeID = Uyeid;
                siparis.Adres = Adres;
                siparis.Fiyat = Fiyat;
                siparis.Durum = "Siparişiniz alındı";
                siparis.Tarih = DateTime.Now.ToString();

               

                db.Siparisler.Add(siparis);
                db.SaveChanges();


                int a = 0;      // Sipariş verirken Sepet temizlenir
                do
                {
                    Sepetim item = db.Sepetim.FirstOrDefault(i => i.UyeID == Uyeid);
                    a = 1;
                    if (item != null)
                    {
                        a = 0;
                        db.Sepetim.Remove(item);
                        db.SaveChanges();
                    }
                } while (a == 0);

                Session["sepet"] = 0;

                return RedirectToAction("Index");
            }

        }
    }
}

TelefonAksesuar/Controllers/UyeOlController.cs
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Globalization;
using System.Threading;
using System.Web.Mvc;
using TelefonAksesuar.Models;
using TelefonAksesuar.ViewModels;

namespace TelefonAksesuar.Controllers
{
    public class UyeOlController : Controller
    {
        public ActionResult Index()
        {
            if (Session["yetki"] == null)
            {
                UyeOlModel model = ModelAl();
                return View(model);
            }
            else
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            
        }

        [HttpPost]
        public ActionResult Index(UyeOlModel model) 
        {
            if (ModelState.IsValid) // formdaki kontroller istenilen şekildeyse ( Required vs gibi)
            {
                TelefonAksesuar.Models.TelefonAksesuarEntities db = new Models.TelefonAksesuarEntities();
                Uyeler uyelerModel = new Uyeler();                      //KAYIT İŞLEMİ      Postla alınanlar ekleniyor
                uyelerModel.Ad = model.Ad;
                uyelerModel.Soyad = model.Soyad;
                uyelerModel.EMail = model.Email;
                uyelerModel.KullaniciAdi = model.KullaniciAdi;
                uyelerModel.Sifre = model.Sifre;
                uyelerModel.Yas = model.Yas;
                uyelerModel.Sehir = model.Sehir;
                uyelerModel.Adres = model.Adres;
                uyelerModel.Yetki = "uye";

                db.Uyeler.Add(uyelerModel);

                db.SaveChanges();

                //MODELİ YENİLİYORUZ EKRANDA MESAJI GÖSTERMEK İÇİN
                ModelState.Clear();
                model = ModelAl();
                model.KullaniciyaMesaj = "Üye kaydınız başarıyla gerçekleşti. Sisteme giriş yapabilirsiniz.";
            }
            
            return View(model);
        }

        // oluşturulan modeli view e göndermek için
        private UyeOlModel ModelAl()
        {
            UyeOlModel model = new UyeOlModel();
            //Veri tabanı bağlantısı
            TelefonAksesuar.Models.TelefonAksesuarEntities db = new Models.TelefonAksesuarEntities();

            return model;
        }


	}
}

TelefonAksesuar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="~/ikon.ico"> 

    <title>Telefon Aksesuar - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    @Scripts.Render("~/bundles/jqueryval")


    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
                <div class="navbar-header"> 
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                       </button>
                        
                         <a href="@Url.Action("Index", "Home")">
                            <img src="@Url.Content("~/Images/amblem.png")" />
                        </a>

</div>
            

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="navbar-collapse collapse in" id="bs-example-navbar-collapse-2" aria-expanded="true">
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["kadi"] != null)
                    {
                        if (Session["yetki"].ToString() == "admin")
                        {

                            <li id="Urunler" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">@TelefonAksesuar.Resources.lang.Ürünler  <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li id="kiliflar">
                                        @Html.ActionLink(TelefonAksesuar.Resources.lang.Kılıflar, "Kiliflar", "Urunler")
                                    </li>
                                    <li id="kulakliklar">
                                        @Html.ActionLink(TelefonAksesuar.Resources.lang.Kulaklıklar, "Kulakliklar", "Urunler")
                                    </li>
                                    <li id="sarjcihazlari">
                                        @Html.ActionLink(TelefonAksesuar.Resources.lang.ŞarjCihazları, "SarjCihazlari", "Urunler")
                                    </li>

                                </ul>
                            </li>

                            <li id="AdminPanel" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">@TelefonAksesuar.Resources.lang.AdminPaneli  <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li id="uyeler">
                                        @Html.ActionLink("Üye Paneli", "Index", "UyeDuzenle")
                                    </li>
                                    <li id="urunler">
                                        @Html.ActionLink("Ürün Paneli", "Index", "UrunDuzenle")
                                    </li>  
                                    <li id="siparisler">
                                        @Html.ActionLink("Sipariş Paneli", "Index", "SiparisDuzenle")
                                    </li>                                   
                                </ul>
                            </li>                            
                            <li id="profil">
                                @Html.ActionLink(TelefonAksesuar.Resources.lang.Profilim, "Index", "Profil")
                            </li>
                            <li id="cikis">
                                @Html.ActionLink(TelefonAksesuar.Resources.lang.Çıkış, "Cikis", "Giris")
                            </li>

                            <li id="mesaj">
                                <span class="label label-danger">@TelefonAksesuar.Resources.lang.Hoşgeldin</span>
                                  <br />
                                <center>
                                    <a href="~/Profil" class="btn btn-danger btn-xs"> @Session["kadi"].ToString()</a> 
                                </center>
                            </li>

                        }
                        else if (Session["yetki"].ToString() == "uye")
                        {

                            <li id="Urunler" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">@TelefonAksesuar.Resources.lang.Ürünler  <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li id="kiliflar">
                                        @Html.ActionLink(TelefonAksesuar.Resources.lang.Kılıflar, "Kiliflar", "Urunler")
                                    </li>
                                    <li id="kulakliklar">
                                        @Html.ActionLink(TelefonAksesuar.Resources.lang.Kulaklıklar, "Kulakliklar", "Urunler")
                                    </li>
                                    <li id="sarjcihazlari">
                                        @Html.ActionLink(TelefonAksesuar.Resources.lang.ŞarjCihazları, "SarjCihazlari", "Urunler")
                                    </li>

                                </ul>
                            </li>

                            <li id="siparis">
                                @Html.ActionLink(TelefonAksesuar.Resources.lang.Siparişlerim, "Index", "Siparis")
                            </li>

                            <li>
                                <a href="~/Sepet">@TelefonAksesuar.Resources.lang.Sepetim <span class="badge">@Session["sepet"]</span></a>
                            </li>
                                <li id="profil">
                                    @Html.ActionLink(TelefonAksesuar.Resources.lang.Profilim, "Index", "Profil")
                                </li>
                                <li id="iletisim">
                                    @Html.ActionLink(TelefonAksesuar.Resources.lang.İletişim, "Index", "Iletisim")
                                </li>
                                <li id="cikis">
                                    @Html.ActionLink(TelefonAksesuar.Resources.lang.Çıkış, "Cikis", "Giris")
                                </li>

                                <li id="mesaj">
                                    <span class="label label-primary disabled">@TelefonAksesuar.Resources.lang.Hoşgeldin</span>
                                    <br />
                                    <center>
                                              <a href="~/Profil" class="btn btn-primary btn-xs"> @Session["kadi"].ToString()</a>                                        
                                    </center>
                                </li>
                        }


                    }
                    else
                    {

                        <li id="giris">
                            @Html.ActionLink(TelefonAksesuar.Resources.lang.Giris, "Index", "Giris") 

                        </li>
                                <li id="uyeol">
                                    @Html.ActionLink(TelefonAksesuar.Resources.lang.UyeOl, "Index", "UyeOl")
                                </li>


                                <li id="Urunler" class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">@TelefonAksesuar.Resources.lang.Ürünler  <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li id="kiliflar">
                                            @Html.ActionLink(TelefonAksesuar.Resources.lang.Kılıflar, "Kiliflar", "Urunler")
                                        </li>
                                        <li id="kulakliklar">
                                            @Html.ActionLink(TelefonAksesuar.Resources.lang.Kulaklıklar, "Kulakliklar", "Urunler")
                                        </li>
                                        <li id="sarjcihazlari">
                                            @Html.ActionLink(TelefonAksesuar.Resources.lang.ŞarjCihazları, "SarjCihazlari", "Urunler")
                                        </li>

                                    </ul>
                                </li>



                                <li id="iletisim">
                                    @Html.ActionLink(TelefonAksesuar.Resources.lang.İletişim, "Index", "Iletisim")
                                </li>

                    }

                    <li id="ara">
                       
                        <div class="navbar-form navbar-left" role="search">
                            <div class="form-group">
                                @using (Html.BeginForm("Index", "Urunler"))
                                {
                                    @Html.TextBox("Arama", null, new { @class = "form-control", style = "width:150px", placeholder = @TelefonAksesuar.Resources.lang.UrunIsmi })

                                    <button type="submit" class="btn btn-default">@TelefonAksesuar.Resources.lang.Ara</button>
                                }
                            </div>

                        </div>

                    </li>


                    <li id="dil" class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">@TelefonAksesuar.Resources.lang.Dil <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("TR", "ChangeCulture", "Home", new { lang = "tr", returnUrl = this.Request.RawUrl }, null)</li>
                            <li>@Html.ActionLink("EN", "ChangeCulture", "Home", new { lang = "en", returnurl = this.Request.RawUrl }, null)</li>
                        </ul>
                    </li>

                </ul>
            </div>

            <!-- /.navbar-collapse -->



        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p align="right">Copyright &copy; 2016-Designed By M.Yaylalı </p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("/js/bootstrap.js")"></script>
    <script src="@Url.Content("/js/modern-business.js")"></script>

    
   

    @RenderSection("scripts", required: false)

</body>
</html>